#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import re
from pathlib import Path
import shutil
import os.path
import logging
import time
import datetime

# Nome do diretório em que estão as imagens
diretorio = '/home/guimoura/Documentos/Organizar/'

start = time.time()

arq_log = "/home/guimoura/Documentos/Organizar/logs/" + str(datetime.date.today()) + ".log"

logging.basicConfig(filename=arq_log, level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s", datefmt="%d/%m/%Y %H:%M:%S")

inicio = datetime.datetime.now().strftime("%d/%m/%Y-%H:%M:%S")
logging.info("")
logging.info("")
logging.info("==================================================================================================================")
logging.info("             START-SCRIPT        Transferindo arquivos " + inicio + "                                             ")
logging.info("==================================================================================================================")
logging.info("")



# Coloca a lista com somente files em arquivos
arquivos = [arquivo for arquivo in os.listdir(diretorio) if os.path.isfile(os.path.join(diretorio, arquivo))]

# quantidade de arquivos para o for
quantidade_arquivos = len(arquivos)

logging.info("==================================================================================================================")
logging.info("                                Quantidade de arquivos a serem transferidos " + str(quantidade_arquivos) + "      ")
logging.info("==================================================================================================================")
logging.info('\n')

logging.info("Começando... ")

if(quantidade_arquivos <= 0):
    logging.info("Não há arquivos para transferencia.")
else:
    for x in range(0, quantidade_arquivos, 1):
        try:
            primeiro_arquivo = arquivos[x]
            logging.info('O nome do arquivo é: {}'.format(primeiro_arquivo))
        except:
            logging.info('Não há arquivos na pasta.')

        if(quantidade_arquivos > 0):
            match = re.search(r'G16_s2023(\d{3})', primeiro_arquivo)
            if match:
                dia = match.group(1)
                diatxt = str(dia).zfill(2)
                destino = Path("/home/guimoura/Documentos/Organizar/dia{}".format(diatxt))
                if not os.path.isdir(destino):
                    logging.info("O diretório dia{} não existe!".format(diatxt))
                    logging.info("Criando diretório dia{}!".format(diatxt))
                    try:
                        os.mkdir(destino)
                        logging.info("Diretório dia{} criado com sucesso!".format(diatxt))
                    except: logging.info("Não foi possível criar a pasta do dia {}".format(diatxt))
                logging.info('Dia a ser transferido {}'.format(diatxt))
            else: 
                logging.info('A sequência "G16_s2023" não foi encontrada no nome do arquivo.')
        
        logging.info('Transferindo arquivos para a pasta dia{}'.format(dia))

        # Caminho do arquivo
        caminho_arquivo = (diretorio + primeiro_arquivo)

        try:
            logging.info("Movendo arquivo...")
            shutil.move(caminho_arquivo, destino)
            logging.info('Concluído!')
        except:
            logging.info('Não foi possível a transferencia do arquivo.')

        logging.info('\n')
        
def finalize(s):
    # Capturando data/hora final
    fim = datetime.datetime.now().strftime("%d/%m/%Y-%H:%M:%S")
    # Realiza o log do calculo do tempo de execucao
    logging.info("")
    logging.info("Tempo gasto " + str(round(time.time() - s, 4)) + ' segundos')
    logging.info("")
    logging.info("==================================================================================================================")
    logging.info("=                 FIM           Tempo de tranferencia de arquivos  " + fim + "                                   =")
    logging.info("==================================================================================================================")
    logging.info("")
    logging.info("")
    logging.info("\n")


finalize(start)
